
GET http://localhost:3000/todos/?priority=HIGH&status=DONE

###
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}

###
PUT http://localhost:3000/todos/1/
Content-Type: application/json

{
    "dueDate": "2022-02-05"
}

###

DELETE http://localhost:3000/todos/1/